[package]
name = "world-gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.21.3"
rand = "0.8.5"
bevy_ecs = "0.10.1"
either = "1.8.1"