[package]
name = "world-gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.21.3"
rand = "0.8.5"
bevy = { version = "0.10.1", default-features = false }
petgraph = "0.6.3"
either = "1.8.1"
replace_with = "0.1.7"