[package]
name = "world-gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.23.0"
rand = "0.8.5"
bevy = { version = "0.11.3", default-features = false }
either = "1.8.1"
replace_with = "0.1.7"